syntax = "proto3";

package pb;

option go_package = "./;pb";






service AuthService {
  rpc Login      (LoginRequest)      returns (LoginResponse);
  rpc VerifyToken(VerifyRequest)     returns (VerifyResponse);
  rpc Register   (SaveUserRequest)   returns (SaveUserResponse);
  rpc CheckUser  (UserRequest)       returns (CheckUserResponse);
}

service CourseService{
  rpc GetUserSections (UserRequest) returns (UserSectionsResponse);
  rpc AddSection (SaveSectionRequest) returns (SaveSectionResponse);
  rpc GetListSubjects(ListSubjectsRequest) returns (ListSubjectsResponse);
}

service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (CreatePaymentResponse);
}

message ListSubjectsRequest{

}
message ListSubjectsResponse {
  repeated string titles = 1;
}

message CreatePaymentRequest {
  string tgid = 1;
  string course_id = 2;
}

message CreatePaymentResponse {
  string payment_id = 1;
  string payment_url = 2;
  string status = 3;
}


message SaveSectionRequest{
  string tgid = 1;
  string title = 2;
}

message SaveSectionResponse{
  bool success = 1;
}

message UserRequest{
  string tgid = 1;
}

message UserSectionsResponse{
  repeated string topic_titles = 1;
}

message LoginRequest{
  string username = 1;
  string password = 2;
}

message LoginResponse{
  string token = 1;
}

message VerifyRequest{
  string token = 1;
}

message VerifyResponse{
  bool valid = 1;
}

message SaveUserRequest {
  string name = 1;
  string tgid = 2;
  string birthdate = 3;
}

message CheckUserResponse {
  bool exists = 1;
}

message SaveUserResponse {
  bool success = 1;
  string message = 2;
}

