syntax = "proto3";

package pb;

option go_package = "./;pb";






service AuthService {
  rpc Login      (LoginRequest)      returns (LoginResponse);
  rpc VerifyToken(VerifyRequest)     returns (VerifyResponse);
  rpc Register   (SaveUserRequest)   returns (SaveUserResponse);
  rpc CheckUser  (UserRequest)       returns (CheckUserResponse);
}

service CourseService{
  rpc MissingSectionsBySubjects (MissingSectionsRequest) returns (MissingSectionsResponse);

  rpc SubjectMissingTotal (SubjectMissingTotalRequest) returns (SubjectMissingTotalResponse);

  rpc GetUserSections (UserRequest) returns (UserSectionsResponse);
  rpc AddSection (SaveSectionRequest) returns (SaveSectionResponse);
  rpc GetListSubjects(ListSubjectsRequest) returns (ListSubjectsResponse);
  rpc GetSubjectSections(SubjectSectionsRequest) returns (SubjectSectionsResponse);
  rpc GetTopicsBySectionTitle (SectionTitleRequest) returns (SectionTopicsResponse);
}
service PaymentService {
  rpc CreatePayment (CreatePaymentRequest) returns (CreatePaymentResponse);
}


message MissingSectionsRequest {
  string tgid = 1;
  repeated string subjects = 2;
}

message MissingSectionsResponse {
  map<string, SubjectMissing> result = 1;
}

message SubjectMissing {
  repeated string section_ids = 1;
}

message SubjectMissingTotalRequest {
  string tgid = 1;
  string subject = 2;
}

message SubjectMissingTotalResponse {
  string subject = 1;
  int64 total_kopeck = 2;
  string currency = 3;
}

message SectionTitleRequest {
  string section_title = 1;
}

message TopicItem {
  int64  id          = 1;
  int64  section_id  = 2;
  string title       = 3;
  string description = 4;
  string tg_id       = 5;
  string mindmap_url = 6;
}

message SectionTopicsResponse {
  repeated TopicItem topics = 1;
}

message SubjectSectionsRequest {
  string tgid = 1;
  string subject = 2;
}

message SectionItem {
  string title = 1;
  bool accessible = 2;
}
message SubjectSectionsResponse {
  repeated SectionItem sections = 1;
}



message ListSubjectsRequest{

}
message ListSubjectsResponse {
  repeated string titles = 1;
}

message CreatePaymentRequest {
  string tgid = 1;
  repeated string course_ids = 2;
}

message CreatePaymentResponse {
  string payment_id = 1;
  string payment_url = 2;
  string status = 3;
}


message SaveSectionRequest{
  string tgid = 1;
  string title = 2;
}

message SaveSectionResponse{
  bool success = 1;
}

message UserRequest{
  string tgid = 1;
}

message UserSectionsResponse{
  repeated string topic_titles = 1;
}

message LoginRequest{
  string username = 1;
  string password = 2;
}

message LoginResponse{
  string token = 1;
}

message VerifyRequest{
  string token = 1;
}

message VerifyResponse{
  bool valid = 1;
}

message SaveUserRequest {
  string name = 1;
  string tgid = 2;
  string birthdate = 3;
}

message CheckUserResponse {
  bool exists = 1;
}

message SaveUserResponse {
  bool success = 1;
  string message = 2;
}

