// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: hello.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceMissingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Sections      []string               `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceMissingRequest) Reset() {
	*x = PriceMissingRequest{}
	mi := &file_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceMissingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceMissingRequest) ProtoMessage() {}

func (x *PriceMissingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceMissingRequest.ProtoReflect.Descriptor instead.
func (*PriceMissingRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{0}
}

func (x *PriceMissingRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *PriceMissingRequest) GetSections() []string {
	if x != nil {
		return x.Sections
	}
	return nil
}

type PriceMissingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MissingSections []string               `protobuf:"bytes,1,rep,name=missing_sections,json=missingSections,proto3" json:"missing_sections,omitempty"`
	TotalKopeck     int64                  `protobuf:"varint,2,opt,name=total_kopeck,json=totalKopeck,proto3" json:"total_kopeck,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriceMissingResponse) Reset() {
	*x = PriceMissingResponse{}
	mi := &file_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceMissingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceMissingResponse) ProtoMessage() {}

func (x *PriceMissingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceMissingResponse.ProtoReflect.Descriptor instead.
func (*PriceMissingResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{1}
}

func (x *PriceMissingResponse) GetMissingSections() []string {
	if x != nil {
		return x.MissingSections
	}
	return nil
}

func (x *PriceMissingResponse) GetTotalKopeck() int64 {
	if x != nil {
		return x.TotalKopeck
	}
	return 0
}

func (x *PriceMissingResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type MissingSectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Subjects      []string               `protobuf:"bytes,2,rep,name=subjects,proto3" json:"subjects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingSectionsRequest) Reset() {
	*x = MissingSectionsRequest{}
	mi := &file_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingSectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingSectionsRequest) ProtoMessage() {}

func (x *MissingSectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingSectionsRequest.ProtoReflect.Descriptor instead.
func (*MissingSectionsRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{2}
}

func (x *MissingSectionsRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *MissingSectionsRequest) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

type MissingSectionsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Result        map[string]*SubjectMissing `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissingSectionsResponse) Reset() {
	*x = MissingSectionsResponse{}
	mi := &file_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissingSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissingSectionsResponse) ProtoMessage() {}

func (x *MissingSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissingSectionsResponse.ProtoReflect.Descriptor instead.
func (*MissingSectionsResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{3}
}

func (x *MissingSectionsResponse) GetResult() map[string]*SubjectMissing {
	if x != nil {
		return x.Result
	}
	return nil
}

type SubjectMissing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionIds    []string               `protobuf:"bytes,1,rep,name=section_ids,json=sectionIds,proto3" json:"section_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectMissing) Reset() {
	*x = SubjectMissing{}
	mi := &file_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectMissing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectMissing) ProtoMessage() {}

func (x *SubjectMissing) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectMissing.ProtoReflect.Descriptor instead.
func (*SubjectMissing) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{4}
}

func (x *SubjectMissing) GetSectionIds() []string {
	if x != nil {
		return x.SectionIds
	}
	return nil
}

type SubjectMissingTotalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectMissingTotalRequest) Reset() {
	*x = SubjectMissingTotalRequest{}
	mi := &file_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectMissingTotalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectMissingTotalRequest) ProtoMessage() {}

func (x *SubjectMissingTotalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectMissingTotalRequest.ProtoReflect.Descriptor instead.
func (*SubjectMissingTotalRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{5}
}

func (x *SubjectMissingTotalRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *SubjectMissingTotalRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SubjectMissingTotalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TotalKopeck   int64                  `protobuf:"varint,2,opt,name=total_kopeck,json=totalKopeck,proto3" json:"total_kopeck,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectMissingTotalResponse) Reset() {
	*x = SubjectMissingTotalResponse{}
	mi := &file_hello_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectMissingTotalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectMissingTotalResponse) ProtoMessage() {}

func (x *SubjectMissingTotalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectMissingTotalResponse.ProtoReflect.Descriptor instead.
func (*SubjectMissingTotalResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{6}
}

func (x *SubjectMissingTotalResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubjectMissingTotalResponse) GetTotalKopeck() int64 {
	if x != nil {
		return x.TotalKopeck
	}
	return 0
}

func (x *SubjectMissingTotalResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type SectionTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionTitle  string                 `protobuf:"bytes,1,opt,name=section_title,json=sectionTitle,proto3" json:"section_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionTitleRequest) Reset() {
	*x = SectionTitleRequest{}
	mi := &file_hello_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionTitleRequest) ProtoMessage() {}

func (x *SectionTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionTitleRequest.ProtoReflect.Descriptor instead.
func (*SectionTitleRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{7}
}

func (x *SectionTitleRequest) GetSectionTitle() string {
	if x != nil {
		return x.SectionTitle
	}
	return ""
}

type TopicItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     int64                  `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	TgId          string                 `protobuf:"bytes,5,opt,name=tg_id,json=tgId,proto3" json:"tg_id,omitempty"`
	MindmapUrl    string                 `protobuf:"bytes,6,opt,name=mindmap_url,json=mindmapUrl,proto3" json:"mindmap_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicItem) Reset() {
	*x = TopicItem{}
	mi := &file_hello_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicItem) ProtoMessage() {}

func (x *TopicItem) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicItem.ProtoReflect.Descriptor instead.
func (*TopicItem) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{8}
}

func (x *TopicItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TopicItem) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *TopicItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TopicItem) GetTgId() string {
	if x != nil {
		return x.TgId
	}
	return ""
}

func (x *TopicItem) GetMindmapUrl() string {
	if x != nil {
		return x.MindmapUrl
	}
	return ""
}

type SectionTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicItem           `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionTopicsResponse) Reset() {
	*x = SectionTopicsResponse{}
	mi := &file_hello_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionTopicsResponse) ProtoMessage() {}

func (x *SectionTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionTopicsResponse.ProtoReflect.Descriptor instead.
func (*SectionTopicsResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{9}
}

func (x *SectionTopicsResponse) GetTopics() []*TopicItem {
	if x != nil {
		return x.Topics
	}
	return nil
}

type SubjectSectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSectionsRequest) Reset() {
	*x = SubjectSectionsRequest{}
	mi := &file_hello_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSectionsRequest) ProtoMessage() {}

func (x *SubjectSectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSectionsRequest.ProtoReflect.Descriptor instead.
func (*SubjectSectionsRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{10}
}

func (x *SubjectSectionsRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *SubjectSectionsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type SectionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Accessible    bool                   `protobuf:"varint,2,opt,name=accessible,proto3" json:"accessible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionItem) Reset() {
	*x = SectionItem{}
	mi := &file_hello_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionItem) ProtoMessage() {}

func (x *SectionItem) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionItem.ProtoReflect.Descriptor instead.
func (*SectionItem) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{11}
}

func (x *SectionItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SectionItem) GetAccessible() bool {
	if x != nil {
		return x.Accessible
	}
	return false
}

type SubjectSectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*SectionItem         `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectSectionsResponse) Reset() {
	*x = SubjectSectionsResponse{}
	mi := &file_hello_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectSectionsResponse) ProtoMessage() {}

func (x *SubjectSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectSectionsResponse.ProtoReflect.Descriptor instead.
func (*SubjectSectionsResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{12}
}

func (x *SubjectSectionsResponse) GetSections() []*SectionItem {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ListSubjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectsRequest) Reset() {
	*x = ListSubjectsRequest{}
	mi := &file_hello_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsRequest) ProtoMessage() {}

func (x *ListSubjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsRequest.ProtoReflect.Descriptor instead.
func (*ListSubjectsRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{13}
}

type ListSubjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Titles        []string               `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubjectsResponse) Reset() {
	*x = ListSubjectsResponse{}
	mi := &file_hello_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubjectsResponse) ProtoMessage() {}

func (x *ListSubjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubjectsResponse.ProtoReflect.Descriptor instead.
func (*ListSubjectsResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{14}
}

func (x *ListSubjectsResponse) GetTitles() []string {
	if x != nil {
		return x.Titles
	}
	return nil
}

type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	CourseIds     []string               `protobuf:"bytes,2,rep,name=course_ids,json=courseIds,proto3" json:"course_ids,omitempty"`
	AmountKopeck  int64                  `protobuf:"varint,3,opt,name=amount_kopeck,json=amountKopeck,proto3" json:"amount_kopeck,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_hello_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePaymentRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *CreatePaymentRequest) GetCourseIds() []string {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

func (x *CreatePaymentRequest) GetAmountKopeck() int64 {
	if x != nil {
		return x.AmountKopeck
	}
	return 0
}

func (x *CreatePaymentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,2,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_hello_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SaveSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSectionRequest) Reset() {
	*x = SaveSectionRequest{}
	mi := &file_hello_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSectionRequest) ProtoMessage() {}

func (x *SaveSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSectionRequest.ProtoReflect.Descriptor instead.
func (*SaveSectionRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{17}
}

func (x *SaveSectionRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *SaveSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SaveSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSectionResponse) Reset() {
	*x = SaveSectionResponse{}
	mi := &file_hello_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSectionResponse) ProtoMessage() {}

func (x *SaveSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSectionResponse.ProtoReflect.Descriptor instead.
func (*SaveSectionResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{18}
}

func (x *SaveSectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tgid          string                 `protobuf:"bytes,1,opt,name=tgid,proto3" json:"tgid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_hello_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{19}
}

func (x *UserRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

type UserSectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicTitles   []string               `protobuf:"bytes,1,rep,name=topic_titles,json=topicTitles,proto3" json:"topic_titles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSectionsResponse) Reset() {
	*x = UserSectionsResponse{}
	mi := &file_hello_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSectionsResponse) ProtoMessage() {}

func (x *UserSectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSectionsResponse.ProtoReflect.Descriptor instead.
func (*UserSectionsResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{20}
}

func (x *UserSectionsResponse) GetTopicTitles() []string {
	if x != nil {
		return x.TopicTitles
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_hello_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{21}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_hello_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{22}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_hello_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{23}
}

func (x *VerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_hello_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{24}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type SaveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tgid          string                 `protobuf:"bytes,2,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserRequest) Reset() {
	*x = SaveUserRequest{}
	mi := &file_hello_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserRequest) ProtoMessage() {}

func (x *SaveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserRequest.ProtoReflect.Descriptor instead.
func (*SaveUserRequest) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{25}
}

func (x *SaveUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveUserRequest) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *SaveUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserResponse) Reset() {
	*x = CheckUserResponse{}
	mi := &file_hello_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserResponse) ProtoMessage() {}

func (x *CheckUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserResponse.ProtoReflect.Descriptor instead.
func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{26}
}

func (x *CheckUserResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type IsAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAdmin       bool                   `protobuf:"varint,1,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	mi := &file_hello_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{27}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type SaveUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserResponse) Reset() {
	*x = SaveUserResponse{}
	mi := &file_hello_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserResponse) ProtoMessage() {}

func (x *SaveUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserResponse.ProtoReflect.Descriptor instead.
func (*SaveUserResponse) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{28}
}

func (x *SaveUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tgid          string                 `protobuf:"bytes,2,opt,name=tgid,proto3" json:"tgid,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_hello_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hello_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_hello_proto_rawDescGZIP(), []int{29}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetTgid() string {
	if x != nil {
		return x.Tgid
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_hello_proto protoreflect.FileDescriptor

const file_hello_proto_rawDesc = "" +
	"\n" +
	"\vhello.proto\x12\x02pb\"E\n" +
	"\x13PriceMissingRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x1a\n" +
	"\bsections\x18\x02 \x03(\tR\bsections\"\x80\x01\n" +
	"\x14PriceMissingResponse\x12)\n" +
	"\x10missing_sections\x18\x01 \x03(\tR\x0fmissingSections\x12!\n" +
	"\ftotal_kopeck\x18\x02 \x01(\x03R\vtotalKopeck\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"H\n" +
	"\x16MissingSectionsRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x1a\n" +
	"\bsubjects\x18\x02 \x03(\tR\bsubjects\"\xa9\x01\n" +
	"\x17MissingSectionsResponse\x12?\n" +
	"\x06result\x18\x01 \x03(\v2'.pb.MissingSectionsResponse.ResultEntryR\x06result\x1aM\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.pb.SubjectMissingR\x05value:\x028\x01\"1\n" +
	"\x0eSubjectMissing\x12\x1f\n" +
	"\vsection_ids\x18\x01 \x03(\tR\n" +
	"sectionIds\"J\n" +
	"\x1aSubjectMissingTotalRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"v\n" +
	"\x1bSubjectMissingTotalResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12!\n" +
	"\ftotal_kopeck\x18\x02 \x01(\x03R\vtotalKopeck\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\":\n" +
	"\x13SectionTitleRequest\x12#\n" +
	"\rsection_title\x18\x01 \x01(\tR\fsectionTitle\"\xa8\x01\n" +
	"\tTopicItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x03R\tsectionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x13\n" +
	"\x05tg_id\x18\x05 \x01(\tR\x04tgId\x12\x1f\n" +
	"\vmindmap_url\x18\x06 \x01(\tR\n" +
	"mindmapUrl\">\n" +
	"\x15SectionTopicsResponse\x12%\n" +
	"\x06topics\x18\x01 \x03(\v2\r.pb.TopicItemR\x06topics\"F\n" +
	"\x16SubjectSectionsRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\"C\n" +
	"\vSectionItem\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"accessible\x18\x02 \x01(\bR\n" +
	"accessible\"F\n" +
	"\x17SubjectSectionsResponse\x12+\n" +
	"\bsections\x18\x01 \x03(\v2\x0f.pb.SectionItemR\bsections\"\x15\n" +
	"\x13ListSubjectsRequest\".\n" +
	"\x14ListSubjectsResponse\x12\x16\n" +
	"\x06titles\x18\x01 \x03(\tR\x06titles\"\x84\x01\n" +
	"\x14CreatePaymentRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x1d\n" +
	"\n" +
	"course_ids\x18\x02 \x03(\tR\tcourseIds\x12#\n" +
	"\ramount_kopeck\x18\x03 \x01(\x03R\famountKopeck\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"o\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1f\n" +
	"\vpayment_url\x18\x02 \x01(\tR\n" +
	"paymentUrl\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\">\n" +
	"\x12SaveSectionRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"/\n" +
	"\x13SaveSectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\vUserRequest\x12\x12\n" +
	"\x04tgid\x18\x01 \x01(\tR\x04tgid\"9\n" +
	"\x14UserSectionsResponse\x12!\n" +
	"\ftopic_titles\x18\x01 \x03(\tR\vtopicTitles\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\rVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"&\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"O\n" +
	"\x0fSaveUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tgid\x18\x02 \x01(\tR\x04tgid\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"+\n" +
	"\x11CheckUserResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\",\n" +
	"\x0fIsAdminResponse\x12\x19\n" +
	"\bis_admin\x18\x01 \x01(\bR\aisAdmin\"F\n" +
	"\x10SaveUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04tgid\x18\x02 \x01(\tR\x04tgid\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x19\n" +
	"\bis_admin\x18\x04 \x01(\bR\aisAdmin2\xb8\x02\n" +
	"\vAuthService\x12,\n" +
	"\x05Login\x12\x10.pb.LoginRequest\x1a\x11.pb.LoginResponse\x124\n" +
	"\vVerifyToken\x12\x11.pb.VerifyRequest\x1a\x12.pb.VerifyResponse\x125\n" +
	"\bRegister\x12\x13.pb.SaveUserRequest\x1a\x14.pb.SaveUserResponse\x123\n" +
	"\tCheckUser\x12\x0f.pb.UserRequest\x1a\x15.pb.CheckUserResponse\x12/\n" +
	"\aIsAdmin\x12\x0f.pb.UserRequest\x1a\x13.pb.IsAdminResponse\x12(\n" +
	"\aGetUser\x12\x0f.pb.UserRequest\x1a\f.pb.UserInfo2\xe9\x04\n" +
	"\rCourseService\x12T\n" +
	"\x19MissingSectionsBySubjects\x12\x1a.pb.MissingSectionsRequest\x1a\x1b.pb.MissingSectionsResponse\x12I\n" +
	"\x14PriceMissingFromList\x12\x17.pb.PriceMissingRequest\x1a\x18.pb.PriceMissingResponse\x12V\n" +
	"\x13SubjectMissingTotal\x12\x1e.pb.SubjectMissingTotalRequest\x1a\x1f.pb.SubjectMissingTotalResponse\x12<\n" +
	"\x0fGetUserSections\x12\x0f.pb.UserRequest\x1a\x18.pb.UserSectionsResponse\x12=\n" +
	"\n" +
	"AddSection\x12\x16.pb.SaveSectionRequest\x1a\x17.pb.SaveSectionResponse\x12D\n" +
	"\x0fGetListSubjects\x12\x17.pb.ListSubjectsRequest\x1a\x18.pb.ListSubjectsResponse\x12M\n" +
	"\x12GetSubjectSections\x12\x1a.pb.SubjectSectionsRequest\x1a\x1b.pb.SubjectSectionsResponse\x12M\n" +
	"\x17GetTopicsBySectionTitle\x12\x17.pb.SectionTitleRequest\x1a\x19.pb.SectionTopicsResponse2V\n" +
	"\x0ePaymentService\x12D\n" +
	"\rCreatePayment\x12\x18.pb.CreatePaymentRequest\x1a\x19.pb.CreatePaymentResponseB\aZ\x05./;pbb\x06proto3"

var (
	file_hello_proto_rawDescOnce sync.Once
	file_hello_proto_rawDescData []byte
)

func file_hello_proto_rawDescGZIP() []byte {
	file_hello_proto_rawDescOnce.Do(func() {
		file_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hello_proto_rawDesc), len(file_hello_proto_rawDesc)))
	})
	return file_hello_proto_rawDescData
}

var file_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_hello_proto_goTypes = []any{
	(*PriceMissingRequest)(nil),         // 0: pb.PriceMissingRequest
	(*PriceMissingResponse)(nil),        // 1: pb.PriceMissingResponse
	(*MissingSectionsRequest)(nil),      // 2: pb.MissingSectionsRequest
	(*MissingSectionsResponse)(nil),     // 3: pb.MissingSectionsResponse
	(*SubjectMissing)(nil),              // 4: pb.SubjectMissing
	(*SubjectMissingTotalRequest)(nil),  // 5: pb.SubjectMissingTotalRequest
	(*SubjectMissingTotalResponse)(nil), // 6: pb.SubjectMissingTotalResponse
	(*SectionTitleRequest)(nil),         // 7: pb.SectionTitleRequest
	(*TopicItem)(nil),                   // 8: pb.TopicItem
	(*SectionTopicsResponse)(nil),       // 9: pb.SectionTopicsResponse
	(*SubjectSectionsRequest)(nil),      // 10: pb.SubjectSectionsRequest
	(*SectionItem)(nil),                 // 11: pb.SectionItem
	(*SubjectSectionsResponse)(nil),     // 12: pb.SubjectSectionsResponse
	(*ListSubjectsRequest)(nil),         // 13: pb.ListSubjectsRequest
	(*ListSubjectsResponse)(nil),        // 14: pb.ListSubjectsResponse
	(*CreatePaymentRequest)(nil),        // 15: pb.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),       // 16: pb.CreatePaymentResponse
	(*SaveSectionRequest)(nil),          // 17: pb.SaveSectionRequest
	(*SaveSectionResponse)(nil),         // 18: pb.SaveSectionResponse
	(*UserRequest)(nil),                 // 19: pb.UserRequest
	(*UserSectionsResponse)(nil),        // 20: pb.UserSectionsResponse
	(*LoginRequest)(nil),                // 21: pb.LoginRequest
	(*LoginResponse)(nil),               // 22: pb.LoginResponse
	(*VerifyRequest)(nil),               // 23: pb.VerifyRequest
	(*VerifyResponse)(nil),              // 24: pb.VerifyResponse
	(*SaveUserRequest)(nil),             // 25: pb.SaveUserRequest
	(*CheckUserResponse)(nil),           // 26: pb.CheckUserResponse
	(*IsAdminResponse)(nil),             // 27: pb.IsAdminResponse
	(*SaveUserResponse)(nil),            // 28: pb.SaveUserResponse
	(*UserInfo)(nil),                    // 29: pb.UserInfo
	nil,                                 // 30: pb.MissingSectionsResponse.ResultEntry
}
var file_hello_proto_depIdxs = []int32{
	30, // 0: pb.MissingSectionsResponse.result:type_name -> pb.MissingSectionsResponse.ResultEntry
	8,  // 1: pb.SectionTopicsResponse.topics:type_name -> pb.TopicItem
	11, // 2: pb.SubjectSectionsResponse.sections:type_name -> pb.SectionItem
	4,  // 3: pb.MissingSectionsResponse.ResultEntry.value:type_name -> pb.SubjectMissing
	21, // 4: pb.AuthService.Login:input_type -> pb.LoginRequest
	23, // 5: pb.AuthService.VerifyToken:input_type -> pb.VerifyRequest
	25, // 6: pb.AuthService.Register:input_type -> pb.SaveUserRequest
	19, // 7: pb.AuthService.CheckUser:input_type -> pb.UserRequest
	19, // 8: pb.AuthService.IsAdmin:input_type -> pb.UserRequest
	19, // 9: pb.AuthService.GetUser:input_type -> pb.UserRequest
	2,  // 10: pb.CourseService.MissingSectionsBySubjects:input_type -> pb.MissingSectionsRequest
	0,  // 11: pb.CourseService.PriceMissingFromList:input_type -> pb.PriceMissingRequest
	5,  // 12: pb.CourseService.SubjectMissingTotal:input_type -> pb.SubjectMissingTotalRequest
	19, // 13: pb.CourseService.GetUserSections:input_type -> pb.UserRequest
	17, // 14: pb.CourseService.AddSection:input_type -> pb.SaveSectionRequest
	13, // 15: pb.CourseService.GetListSubjects:input_type -> pb.ListSubjectsRequest
	10, // 16: pb.CourseService.GetSubjectSections:input_type -> pb.SubjectSectionsRequest
	7,  // 17: pb.CourseService.GetTopicsBySectionTitle:input_type -> pb.SectionTitleRequest
	15, // 18: pb.PaymentService.CreatePayment:input_type -> pb.CreatePaymentRequest
	22, // 19: pb.AuthService.Login:output_type -> pb.LoginResponse
	24, // 20: pb.AuthService.VerifyToken:output_type -> pb.VerifyResponse
	28, // 21: pb.AuthService.Register:output_type -> pb.SaveUserResponse
	26, // 22: pb.AuthService.CheckUser:output_type -> pb.CheckUserResponse
	27, // 23: pb.AuthService.IsAdmin:output_type -> pb.IsAdminResponse
	29, // 24: pb.AuthService.GetUser:output_type -> pb.UserInfo
	3,  // 25: pb.CourseService.MissingSectionsBySubjects:output_type -> pb.MissingSectionsResponse
	1,  // 26: pb.CourseService.PriceMissingFromList:output_type -> pb.PriceMissingResponse
	6,  // 27: pb.CourseService.SubjectMissingTotal:output_type -> pb.SubjectMissingTotalResponse
	20, // 28: pb.CourseService.GetUserSections:output_type -> pb.UserSectionsResponse
	18, // 29: pb.CourseService.AddSection:output_type -> pb.SaveSectionResponse
	14, // 30: pb.CourseService.GetListSubjects:output_type -> pb.ListSubjectsResponse
	12, // 31: pb.CourseService.GetSubjectSections:output_type -> pb.SubjectSectionsResponse
	9,  // 32: pb.CourseService.GetTopicsBySectionTitle:output_type -> pb.SectionTopicsResponse
	16, // 33: pb.PaymentService.CreatePayment:output_type -> pb.CreatePaymentResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hello_proto_init() }
func file_hello_proto_init() {
	if File_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hello_proto_rawDesc), len(file_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_hello_proto_goTypes,
		DependencyIndexes: file_hello_proto_depIdxs,
		MessageInfos:      file_hello_proto_msgTypes,
	}.Build()
	File_hello_proto = out.File
	file_hello_proto_goTypes = nil
	file_hello_proto_depIdxs = nil
}
